/**
 * The Settings window's tabs, as documented on the website (issue #1010).
 *
 * ONE source of truth, consumed by three things: the capture harness (which
 * pane to click and what to name the PNG), the freshness test (which asserts
 * this list still matches the built page's `data-pane` buttons), and the docs
 * page itself (whose sections are named after `label`).
 *
 * `pane` is the value of a nav button's `data-pane` attribute in
 * `settings-window.ejs`; `file` is deliberately spelled out rather than
 * derived from it, because two of them differ — the pane ids `bindings` and
 * `updates` read as `key-bindings.png` and `whats-new.png` in the docs, which
 * is what a reader looking at the asset folder expects to find.
 */

/**
 * @typedef {object} SettingsWindowTab
 * @property {string} pane - `data-pane` value of the nav button.
 * @property {string} label - Nav button text, and the docs section heading.
 * @property {string} file - Screenshot filename, without a directory.
 * @property {boolean} elgatoOnly - Rendered only when the `profiles` platform
 *   flag is on, so the capture must run against the Stream Deck plugin build.
 */

/** @type {readonly SettingsWindowTab[]} */
export const SETTINGS_WINDOW_TABS = [
  { pane: "getting-started", label: "Getting Started", file: "getting-started.png", elgatoOnly: false },
  { pane: "general", label: "General", file: "general.png", elgatoOnly: false },
  { pane: "bindings", label: "Key Bindings", file: "key-bindings.png", elgatoOnly: false },
  { pane: "appearance", label: "Appearance", file: "appearance.png", elgatoOnly: false },
  { pane: "engineer", label: "Race Engineer", file: "race-engineer.png", elgatoOnly: false },
  { pane: "profiles", label: "Profiles", file: "profiles.png", elgatoOnly: true },
  { pane: "delays", label: "Delays", file: "delays.png", elgatoOnly: false },
  { pane: "simhub", label: "SimHub", file: "simhub.png", elgatoOnly: false },
  { pane: "updates", label: "What's New", file: "whats-new.png", elgatoOnly: false },
  { pane: "diagnostics", label: "Diagnostics", file: "diagnostics.png", elgatoOnly: false },
];

/**
 * Every `data-pane` value in a rendered settings-window page, in document
 * order. Used by the freshness test to compare the built page against
 * {@link SETTINGS_WINDOW_TABS}; a regex rather than a DOM parse keeps this
 * dependency-free, and the markup it matches is generated by our own template.
 *
 * Attribute ORDER is not assumed: a nav button may legitimately carry an `id`
 * or anything else between its class and its `data-pane` (the What's New
 * button gained one in #1016 so the update badge can be found).
 *
 * @param {string} html - The built `settings-window.html`.
 * @returns {string[]} Pane ids of the nav buttons.
 */
export function parseNavPanes(html) {
  const panes = [];

  for (const tag of html.matchAll(/<button[^>]*class="sw-nav-item[^"]*"[^>]*>/g)) {
    const pane = /\sdata-pane="([a-z-]+)"/.exec(tag[0]);

    if (pane) panes.push(pane[1]);
  }

  return panes;
}
