/**
 * Everything the bootstrap takes from `@iracedeck/iracing-actions`: the
 * plugin-level hooks, and the actions every plugin registers. The only importer
 * of that package in plugin-runtime, so tests mock one file.
 */
import {
  AI_SPOTTER_CONTROLS_UUID,
  AiSpotterControls,
  AUDIO_CONTROLS_UUID,
  AudioControls,
  BLACK_BOX_SELECTOR_UUID,
  BlackBoxSelector,
  CAMERA_CONTROLS_UUID,
  CAMERA_EDITOR_ADJUSTMENTS_UUID,
  CAMERA_EDITOR_CONTROLS_UUID,
  CameraControls,
  CameraEditorAdjustments,
  CameraEditorControls,
  CAR_CONTROL_UUID,
  CarControl,
  Chat,
  CHAT_UUID,
  COCKPIT_MISC_UUID,
  CockpitMisc,
  FORCE_FEEDBACK_UUID,
  ForceFeedback,
  FUEL_SERVICE_UUID,
  FuelService,
  LOOK_DIRECTION_UUID,
  LookDirection,
  MEDIA_CAPTURE_UUID,
  MediaCapture,
  PIT_CREW_UUID,
  PIT_QUICK_ACTIONS_UUID,
  PitCrew,
  PitQuickActions,
  RACE_ADMIN_UUID,
  RaceAdmin,
  REPLAY_CONTROL_UUID,
  REPLAY_MARKERS_UUID,
  REPLAY_NAVIGATION_UUID,
  REPLAY_SPEED_UUID,
  REPLAY_TRANSPORT_UUID,
  ReplayControl,
  ReplayMarkers,
  ReplayNavigation,
  ReplaySpeed,
  ReplayTransport,
  SESSION_INFO_UUID,
  SessionInfo,
  SETUP_AERO_UUID,
  SETUP_BRAKES_UUID,
  SETUP_CHASSIS_UUID,
  SETUP_ENGINE_UUID,
  SETUP_FUEL_UUID,
  SETUP_HYBRID_UUID,
  SETUP_TRACTION_UUID,
  SetupAero,
  SetupBrakes,
  SetupChassis,
  SetupEngine,
  SetupFuel,
  SetupHybrid,
  SetupTraction,
  SPLITS_DELTA_CYCLE_UUID,
  SplitsDeltaCycle,
  SWITCH_PROFILE_UUID,
  SwitchProfile,
  TELEMETRY_CONTROL_UUID,
  TELEMETRY_DISPLAY_UUID,
  TelemetryControl,
  TelemetryDisplay,
  TIRE_SERVICE_UUID,
  TireService,
  TOGGLE_UI_ELEMENTS_UUID,
  ToggleUiElements,
  VIEW_ADJUSTMENT_UUID,
  ViewAdjustment,
} from "@iracedeck/iracing-actions";

import type { ActionRegistration } from "./types.js";

export {
  applyRaceEngineerAudio,
  applyRadarEnabled,
  applyRadarVolume,
  armFeatureGateSync,
  CAR_CYCLE_BINDING_DEFAULTS,
  isAudioPreviewKind,
  migrateLfeIntensityBindingKeys,
  runAudioPreview,
  SETUP_CHASSIS_BINDING_KEY_RENAMES,
  stopRaceEngineerPlayback,
  syncFeatureGates,
} from "@iracedeck/iracing-actions";

/**
 * Every action all three plugins register, in registration order (#1349).
 * `scope` is the logger scope each always used. A new action goes here and
 * in every manifest — `actions.test.ts` fails until they agree.
 */
export const SHARED_ACTIONS: readonly ActionRegistration[] = [
  { uuid: AI_SPOTTER_CONTROLS_UUID, scope: "AiSpotterControls", create: (logger) => new AiSpotterControls(logger) },
  { uuid: AUDIO_CONTROLS_UUID, scope: "AudioControls", create: (logger) => new AudioControls(logger) },
  { uuid: BLACK_BOX_SELECTOR_UUID, scope: "BlackBoxSelector", create: (logger) => new BlackBoxSelector(logger) },
  { uuid: CAMERA_CONTROLS_UUID, scope: "CameraControls", create: (logger) => new CameraControls(logger) },
  // Legacy UUID — existing Camera Cycle buttons continue to work after merge into Camera Controls
  {
    uuid: "com.iracedeck.sd.core.camera-cycle",
    scope: "CameraControls",
    create: (logger) => new CameraControls(logger),
  },
  {
    uuid: CAMERA_EDITOR_ADJUSTMENTS_UUID,
    scope: "CameraEditorAdjustments",
    create: (logger) => new CameraEditorAdjustments(logger),
  },
  {
    uuid: CAMERA_EDITOR_CONTROLS_UUID,
    scope: "CameraEditorControls",
    create: (logger) => new CameraEditorControls(logger),
  },
  { uuid: CAR_CONTROL_UUID, scope: "CarControl", create: (logger) => new CarControl(logger) },
  { uuid: CHAT_UUID, scope: "Chat", create: (logger) => new Chat(logger) },
  { uuid: COCKPIT_MISC_UUID, scope: "CockpitMisc", create: (logger) => new CockpitMisc(logger) },
  { uuid: FORCE_FEEDBACK_UUID, scope: "ForceFeedback", create: (logger) => new ForceFeedback(logger) },
  { uuid: FUEL_SERVICE_UUID, scope: "FuelService", create: (logger) => new FuelService(logger) },
  { uuid: LOOK_DIRECTION_UUID, scope: "LookDirection", create: (logger) => new LookDirection(logger) },
  { uuid: MEDIA_CAPTURE_UUID, scope: "MediaCapture", create: (logger) => new MediaCapture(logger) },
  { uuid: PIT_CREW_UUID, scope: "PitCrew", create: (logger) => new PitCrew(logger) },
  { uuid: PIT_QUICK_ACTIONS_UUID, scope: "PitQuickActions", create: (logger) => new PitQuickActions(logger) },
  { uuid: RACE_ADMIN_UUID, scope: "RaceAdmin", create: (logger) => new RaceAdmin(logger) },
  { uuid: REPLAY_CONTROL_UUID, scope: "ReplayControl", create: (logger) => new ReplayControl(logger) },
  { uuid: REPLAY_MARKERS_UUID, scope: "ReplayMarkers", create: (logger) => new ReplayMarkers(logger) },
  { uuid: REPLAY_NAVIGATION_UUID, scope: "ReplayNavigation", create: (logger) => new ReplayNavigation(logger) },
  { uuid: REPLAY_SPEED_UUID, scope: "ReplaySpeed", create: (logger) => new ReplaySpeed(logger) },
  { uuid: REPLAY_TRANSPORT_UUID, scope: "ReplayTransport", create: (logger) => new ReplayTransport(logger) },
  { uuid: SESSION_INFO_UUID, scope: "SessionInfo", create: (logger) => new SessionInfo(logger) },
  { uuid: SETUP_AERO_UUID, scope: "SetupAero", create: (logger) => new SetupAero(logger) },
  { uuid: SETUP_BRAKES_UUID, scope: "SetupBrakes", create: (logger) => new SetupBrakes(logger) },
  { uuid: SETUP_CHASSIS_UUID, scope: "SetupChassis", create: (logger) => new SetupChassis(logger) },
  { uuid: SETUP_ENGINE_UUID, scope: "SetupEngine", create: (logger) => new SetupEngine(logger) },
  { uuid: SETUP_FUEL_UUID, scope: "SetupFuel", create: (logger) => new SetupFuel(logger) },
  { uuid: SETUP_HYBRID_UUID, scope: "SetupHybrid", create: (logger) => new SetupHybrid(logger) },
  { uuid: SETUP_TRACTION_UUID, scope: "SetupTraction", create: (logger) => new SetupTraction(logger) },
  { uuid: SPLITS_DELTA_CYCLE_UUID, scope: "SplitsDeltaCycle", create: (logger) => new SplitsDeltaCycle(logger) },
  { uuid: TELEMETRY_CONTROL_UUID, scope: "TelemetryControl", create: (logger) => new TelemetryControl(logger) },
  { uuid: TELEMETRY_DISPLAY_UUID, scope: "TelemetryDisplay", create: (logger) => new TelemetryDisplay(logger) },
  { uuid: TIRE_SERVICE_UUID, scope: "TireService", create: (logger) => new TireService(logger) },
  { uuid: TOGGLE_UI_ELEMENTS_UUID, scope: "ToggleUiElements", create: (logger) => new ToggleUiElements(logger) },
  { uuid: VIEW_ADJUSTMENT_UUID, scope: "ViewAdjustment", create: (logger) => new ViewAdjustment(logger) },
];

/** The Stream Deck extension's extras: profile switching is Elgato-only (#736). */
export const STREAM_DECK_ACTIONS: readonly ActionRegistration[] = [
  { uuid: SWITCH_PROFILE_UUID, scope: "SwitchProfile", create: (logger) => new SwitchProfile(logger) },
];
