name: Release

on:
  push:
    tags: ["v*"]

permissions:
  checks: write
  contents: write
  pull-requests: write

jobs:
  build-plugins:
    uses: ./.github/workflows/release-pack.yml
    secrets: inherit
  deploy-website:
    needs: [build-plugins]
    if: ${{ !contains(github.ref_name, '-') }}
    uses: ./.github/workflows/firebase-hosting-release.yml
    secrets: inherit
    with:
      version: ${{ github.ref_name }}
