// Generated by scripts/refresh-corner-data.mjs — do not edit by hand.
// Source: lovely-track-data (Lovely Sim Racing, CC BY-NC-SA 4.0, used with permission — issue #888).
import type { CornerSnapshot } from "./refresh.js";

export const CORNER_SNAPSHOT: CornerSnapshot = {
  adelaide: [
    {
      start: 0.055,
      name: "Turn 1",
    },
    {
      start: 0.083,
      name: "Turn 2",
    },
    {
      start: 0.113,
      name: "Turn 3",
    },
    {
      start: 0.19,
      name: "Turn 4",
    },
    {
      start: 0.245,
      name: "Turn 5",
    },
    {
      start: 0.293,
      name: "Turn 6",
    },
    {
      start: 0.338,
      name: "Turn 7",
    },
    {
      start: 0.53,
      name: "Turn 8",
    },
    {
      start: 0.66,
      name: "Turn 9",
    },
    {
      start: 0.71,
      name: "Turn 10",
    },
    {
      start: 0.75,
      name: "Turn 11",
    },
    {
      start: 0.798,
      name: "Turn 12",
    },
    {
      start: 0.853,
      name: "Turn 13",
    },
    {
      start: 0.9,
      name: "Turn 14",
    },
  ],
  "algarve gp": [
    {
      start: 0.049,
      name: "Turn 4",
    },
    {
      start: 0.124,
      name: "Primeira",
    },
    {
      start: 0.167,
      name: "Turn 2",
    },
    {
      start: 0.194,
      name: "Lagos",
    },
    {
      start: 0.229,
      name: "Turn 4",
    },
    {
      start: 0.355,
      name: "Turn 5",
    },
    {
      start: 0.4,
      name: "Turn 6",
    },
    {
      start: 0.45,
      name: "Turn 7",
    },
    {
      start: 0.487,
      name: "Samsung",
    },
    {
      start: 0.558,
      name: "Turn 9",
    },
    {
      start: 0.618,
      name: "Portimao",
    },
    {
      start: 0.67,
      name: "Turn 12",
    },
    {
      start: 0.728,
      name: "Turn 13",
    },
    {
      start: 0.775,
      name: "Sagres",
    },
    {
      start: 0.85,
      name: "Galp",
    },
  ],
  "barcelona gp": [
    {
      start: 0.167,
      name: "Elf",
    },
    {
      start: 0.226,
      name: "Renault",
    },
    {
      start: 0.345,
      name: "Repsol",
    },
    {
      start: 0.425,
      name: "Seat",
    },
    {
      start: 0.427,
      name: "Turn 6",
    },
    {
      start: 0.525,
      name: "Wuerth",
    },
    {
      start: 0.595,
      name: "Campsa",
    },
    {
      start: 0.731,
      name: "La Caixa",
    },
    {
      start: 0.795,
      name: "Banc Sabadell",
    },
    {
      start: 0.85,
      name: "Europcar",
    },
    {
      start: 0.877,
      name: "Chicane RACC",
    },
    {
      start: 0.916,
      name: "New Holland",
    },
  ],
  "barcelona historic": [
    {
      start: 0.167,
      name: "Elf",
    },
    {
      start: 0.226,
      name: "Renault",
    },
    {
      start: 0.345,
      name: "Repsol",
    },
    {
      start: 0.425,
      name: "Seat",
    },
    {
      start: 0.427,
      name: "Turn 6",
    },
    {
      start: 0.525,
      name: "Wuerth",
    },
    {
      start: 0.595,
      name: "Campsa",
    },
    {
      start: 0.731,
      name: "La Caixa",
    },
    {
      start: 0.795,
      name: "Banc Sabadell",
    },
    {
      start: 0.866,
      name: "Europcar",
    },
    {
      start: 0.921,
      name: "New Holland",
    },
  ],
  bathurst: [
    {
      start: 0.046,
      name: "Hell Corner",
    },
    {
      start: 0.22,
      name: "Quarry Bend",
    },
    {
      start: 0.3,
      name: "The Cutting",
    },
    {
      start: 0.334,
      name: "Griffin's Mount",
    },
    {
      start: 0.365,
      name: "Reid Park",
    },
    {
      start: 0.39,
      name: "Sulman Park",
    },
    {
      start: 0.463,
      name: "McPhillamy Park",
    },
    {
      start: 0.517,
      name: "Skyline",
    },
    {
      start: 0.551,
      name: "The Esses",
    },
    {
      start: 0.6,
      name: "The Dipper",
    },
    {
      start: 0.616,
      name: "Forest's Elbow",
    },
    {
      start: 0.87,
      name: "The Chase",
    },
    {
      start: 0.965,
      name: "Murray's Corner",
    },
  ],
  "brandshatch grandprix": [
    {
      start: 0.035,
      name: "Paddock Hill Bend",
    },
    {
      start: 0.136,
      name: "Druids",
    },
    {
      start: 0.206,
      name: "Graham Hill Bend",
    },
    {
      start: 0.295,
      name: "Surtees",
    },
    {
      start: 0.49,
      name: "Hawthorn Bend",
    },
    {
      start: 0.591,
      name: "Westfield Bend",
    },
    {
      start: 0.664,
      name: "Dingle Dell",
    },
    {
      start: 0.691,
      name: "Sheene's",
    },
    {
      start: 0.749,
      name: "Stirling's",
    },
    {
      start: 0.863,
      name: "Clark Curve",
    },
  ],
  "charlotte 2018 2019 roval": [
    {
      start: 0.03,
      name: "Turn 1",
    },
    {
      start: 0.081,
      name: "Turn 2",
    },
    {
      start: 0.15,
      name: "Turn 3",
    },
    {
      start: 0.19,
      name: "Turn 4",
    },
    {
      start: 0.28,
      name: "Turn 5",
    },
    {
      start: 0.316,
      name: "Turn 6",
    },
    {
      start: 0.355,
      name: "Turn 7",
    },
    {
      start: 0.401,
      name: "Turn 8",
    },
    {
      start: 0.44,
      name: "Turn 9",
    },
    {
      start: 0.506,
      name: "Turn 10",
    },
    {
      start: 0.66,
      name: "Turn 11",
    },
    {
      start: 0.71,
      name: "Turn 12",
    },
    {
      start: 0.751,
      name: "Turn 13",
    },
    {
      start: 0.826,
      name: "Turn 14",
    },
    {
      start: 0.91,
      name: "Turn 15",
    },
    {
      start: 0.945,
      name: "Turn 16",
    },
    {
      start: 0.966,
      name: "Turn 17",
    },
  ],
  "cota-gp": [
    {
      start: 0.105,
      name: "Turn 1",
    },
    {
      start: 0.14,
      name: "Turn 2",
    },
    {
      start: 0.185,
      name: "Turn 3",
    },
    {
      start: 0.22,
      name: "Turn 4",
    },
    {
      start: 0.238,
      name: "Turn 5",
    },
    {
      start: 0.263,
      name: "Turn 6",
    },
    {
      start: 0.298,
      name: "Turn 7",
    },
    {
      start: 0.328,
      name: "Turn 8",
    },
    {
      start: 0.35,
      name: "Turn 9",
    },
    {
      start: 0.38,
      name: "Turn 10",
    },
    {
      start: 0.44,
      name: "Turn 11",
    },
    {
      start: 0.66,
      name: "Turn 12",
    },
    {
      start: 0.708,
      name: "Turn 13",
    },
    {
      start: 0.738,
      name: "Turn 14",
    },
    {
      start: 0.76,
      name: "Turn 15",
    },
    {
      start: 0.775,
      name: "Turn 16",
    },
    {
      start: 0.803,
      name: "Turn 17",
    },
    {
      start: 0.848,
      name: "Turn 18",
    },
    {
      start: 0.893,
      name: "Turn 19",
    },
    {
      start: 0.945,
      name: "Turn 20",
    },
  ],
  "daytona 2011 road": [
    {
      start: 0.085,
      name: "Turn 1",
    },
    {
      start: 0.115,
      name: "Turn 2",
    },
    {
      start: 0.169,
      name: "Turn 3",
    },
    {
      start: 0.255,
      name: "Turn 4",
    },
    {
      start: 0.309,
      name: "Turn 5",
    },
    {
      start: 0.376,
      name: "Turn 6",
    },
    {
      start: 0.451,
      name: "Turn 7",
    },
    {
      start: 0.67,
      name: "Turn 8",
    },
    {
      start: 0.68,
      name: "Turn 9",
    },
    {
      start: 0.692,
      name: "Turn 10",
    },
    {
      start: 0.703,
      name: "Turn 11",
    },
    {
      start: 0.81,
      name: "Turn 12",
    },
  ],
  "donington gp": [
    {
      start: 0.066,
      name: "Redgate",
    },
    {
      start: 0.133,
      name: "Hollywood",
    },
    {
      start: 0.2,
      name: "Craner Curves",
    },
    {
      start: 0.26,
      name: "Old Hairpin",
    },
    {
      start: 0.32,
      name: "Starkey's Bridge",
    },
    {
      start: 0.375,
      name: "Schwantz Curve",
    },
    {
      start: 0.42,
      name: "McLeans",
    },
    {
      start: 0.495,
      name: "Coppice",
    },
    {
      start: 0.696,
      name: "Fogarty Esses",
    },
    {
      start: 0.815,
      name: "Melbourne Hairpin",
    },
    {
      start: 0.915,
      name: "Goddards",
    },
  ],
  "donington national": [
    {
      start: 0.085,
      name: "Redgate",
    },
    {
      start: 0.185,
      name: "Hollywood",
    },
    {
      start: 0.255,
      name: "Craner Curves",
    },
    {
      start: 0.326,
      name: "Old Hairpin",
    },
    {
      start: 0.405,
      name: "Starkey's Bridge",
    },
    {
      start: 0.475,
      name: "Schwantz Curve",
    },
    {
      start: 0.52,
      name: "McLeans",
    },
    {
      start: 0.625,
      name: "Coppice",
    },
    {
      start: 0.865,
      name: "Roberts",
    },
  ],
  "hockenheim gp": [
    {
      start: 0.03,
      name: "Nordkurve",
    },
    {
      start: 0.16,
      name: "Einfahrt Parabolika",
    },
    {
      start: 0.226,
      name: "Parabolika",
    },
    {
      start: 0.43,
      name: "Spitzkehre",
    },
    {
      start: 0.57,
      name: "Mercedes",
    },
    {
      start: 0.725,
      name: "Mobil 1 Kurve",
    },
    {
      start: 0.806,
      name: "Sachs-Kurve",
    },
    {
      start: 0.891,
      name: "Suedkurve",
    },
  ],
  "imola gp": [
    {
      start: 0.025,
      name: "Turn 1",
    },
    {
      start: 0.115,
      name: "Variante Tamburello",
    },
    {
      start: 0.151,
      name: "Variante Tamburello",
    },
    {
      start: 0.186,
      name: "Turn 4",
    },
    {
      start: 0.252,
      name: "Variante Villeneuve",
    },
    {
      start: 0.281,
      name: "Variante Villeneuve",
    },
    {
      start: 0.325,
      name: "Tosa",
    },
    {
      start: 0.432,
      name: "Turn 8",
    },
    {
      start: 0.448,
      name: "Piratella",
    },
    {
      start: 0.519,
      name: "Turn 10",
    },
    {
      start: 0.54,
      name: "Acque Minerali",
    },
    {
      start: 0.575,
      name: "Acque Minerali",
    },
    {
      start: 0.607,
      name: "Turn 13",
    },
    {
      start: 0.655,
      name: "GRESINI",
    },
    {
      start: 0.69,
      name: "GRESINI",
    },
    {
      start: 0.806,
      name: "Turn 16",
    },
    {
      start: 0.818,
      name: "Rivazza",
    },
    {
      start: 0.846,
      name: "Turn 17",
    },
    {
      start: 0.939,
      name: "Turn 20",
    },
  ],
  "indianapolis 2022 road": [
    {
      start: 0.15,
      name: "Turn 1",
    },
    {
      start: 0.184,
      name: "Turn 2",
    },
    {
      start: 0.21,
      name: "Turn 3",
    },
    {
      start: 0.255,
      name: "Turn 4",
    },
    {
      start: 0.309,
      name: "Turn 5",
    },
    {
      start: 0.327,
      name: "Turn 6",
    },
    {
      start: 0.51,
      name: "Turn 7",
    },
    {
      start: 0.55,
      name: "Turn 8",
    },
    {
      start: 0.58,
      name: "Turn 9",
    },
    {
      start: 0.605,
      name: "Turn 10",
    },
    {
      start: 0.675,
      name: "Turn 11",
    },
    {
      start: 0.77,
      name: "Turn 12",
    },
    {
      start: 0.81,
      name: "Turn 13",
    },
    {
      start: 0.85,
      name: "Turn 14",
    },
  ],
  "interlagos gp": [
    {
      start: 0.045,
      name: "S do Senna",
    },
    {
      start: 0.114,
      name: "Curva do Sol",
    },
    {
      start: 0.298,
      name: "Descida do Lago",
    },
    {
      start: 0.456,
      name: "Ferradura",
    },
    {
      start: 0.488,
      name: "Laranjinha",
    },
    {
      start: 0.525,
      name: "Esse",
    },
    {
      start: 0.557,
      name: "Pinheirinho",
    },
    {
      start: 0.622,
      name: "Bico de Pato",
    },
    {
      start: 0.659,
      name: "Mergulho",
    },
    {
      start: 0.734,
      name: "Juncao",
    },
    {
      start: 0.771,
      name: "Turn 13",
    },
    {
      start: 0.815,
      name: "Turn 14",
    },
    {
      start: 0.9,
      name: "Turn 15",
    },
  ],
  "jerez gp": [
    {
      start: 0.03,
      name: "Expo 92",
    },
    {
      start: 0.095,
      name: "Michelin",
    },
    {
      start: 0.25,
      name: "Sito Pons",
    },
    {
      start: 0.435,
      name: "Dry Sack",
    },
    {
      start: 0.47,
      name: "Aspar",
    },
    {
      start: 0.65,
      name: "Angel Nieto",
    },
    {
      start: 0.696,
      name: "Peluqui",
    },
    {
      start: 0.752,
      name: "Ayrton Senna Chicane",
    },
    {
      start: 0.817,
      name: "Ferrari",
    },
    {
      start: 0.872,
      name: "Lorenzo",
    },
  ],
  "jerez moto": [
    {
      start: 0.03,
      name: "Expo 92",
    },
    {
      start: 0.095,
      name: "Michelin",
    },
    {
      start: 0.25,
      name: "Sito Pons",
    },
    {
      start: 0.435,
      name: "Dry Sack",
    },
    {
      start: 0.47,
      name: "Aspar",
    },
    {
      start: 0.65,
      name: "Angel Nieto",
    },
    {
      start: 0.696,
      name: "Peluqui",
    },
    {
      start: 0.752,
      name: "Alex Criville",
    },
    {
      start: 0.817,
      name: "Ferrari",
    },
    {
      start: 0.872,
      name: "Lorenzo",
    },
  ],
  lagunaseca: [
    {
      start: 0.045,
      name: "Turn 1",
    },
    {
      start: 0.1,
      name: "Andretti Hairpin",
    },
    {
      start: 0.191,
      name: "Turn 3",
    },
    {
      start: 0.265,
      name: "Turn 4",
    },
    {
      start: 0.4,
      name: "Turn 5",
    },
    {
      start: 0.52,
      name: "Turn 6",
    },
    {
      start: 0.661,
      name: "The Corkscrew",
    },
    {
      start: 0.725,
      name: "Turn 9",
    },
    {
      start: 0.805,
      name: "Turn 10",
    },
    {
      start: 0.89,
      name: "Turn 11",
    },
  ],
  "lagunaseca school": [
    {
      start: 0.045,
      name: "Turn 1",
    },
    {
      start: 0.1,
      name: "Andretti Hairpin",
    },
    {
      start: 0.191,
      name: "Turn 3",
    },
    {
      start: 0.265,
      name: "Turn 4",
    },
    {
      start: 0.4,
      name: "Turn 5",
    },
    {
      start: 0.52,
      name: "Turn 6",
    },
    {
      start: 0.661,
      name: "The Corkscrew",
    },
    {
      start: 0.725,
      name: "Turn 9",
    },
    {
      start: 0.805,
      name: "Turn 10",
    },
    {
      start: 0.89,
      name: "Turn 11",
    },
  ],
  ledenon: [
    {
      start: 0.047,
      name: "Triple Gauche",
    },
    {
      start: 0.231,
      name: "Virage du Pont",
    },
    {
      start: 0.348,
      name: "La Carrierasse",
    },
    {
      start: 0.399,
      name: "La Courmelle",
    },
    {
      start: 0.484,
      name: "Virage du Camion",
    },
    {
      start: 0.531,
      name: "Le Cavalet",
    },
    {
      start: 0.675,
      name: "La servie",
    },
    {
      start: 0.827,
      name: "La cuvette",
    },
  ],
  "lemans full": [
    {
      start: 0.04,
      name: "Courbe Dunlop",
    },
    {
      start: 0.057,
      name: "Ralentisseur Dunlop",
    },
    {
      start: 0.077,
      name: "Descente de la Chapelle",
    },
    {
      start: 0.087,
      name: "S du Tetre Rouge",
    },
    {
      start: 0.133,
      name: "Virage du Tertre Rouge",
    },
    {
      start: 0.182,
      name: "Courbe d'Antares",
    },
    {
      start: 0.284,
      name: "1er Ralentisseur",
    },
    {
      start: 0.431,
      name: "2e Ralentisseur",
    },
    {
      start: 0.468,
      name: "Courbe des Hunaudieres",
    },
    {
      start: 0.55,
      name: "Virage de Mulsanne",
    },
    {
      start: 0.61,
      name: "Courbe du Golf",
    },
    {
      start: 0.695,
      name: "Esses d'Indianapolis",
    },
    {
      start: 0.74,
      name: "Virage d'Arnage",
    },
    {
      start: 0.77,
      name: "Courbe du Buisson",
    },
    {
      start: 0.829,
      name: "Virage Porsche",
    },
    {
      start: 0.856,
      name: "Virage du Pont",
    },
    {
      start: 0.877,
      name: "Esses du Karting",
    },
    {
      start: 0.907,
      name: "Virage Corvette",
    },
    {
      start: 0.933,
      name: "Maison Blanche",
    },
    {
      start: 0.968,
      name: "Virage Ford",
    },
    {
      start: 0.98,
      name: "Virage du Raccordement",
    },
  ],
  "lemans nochicane": [
    {
      start: 0.04,
      name: "Courbe Dunlop",
    },
    {
      start: 0.057,
      name: "Ralentisseur Dunlop",
    },
    {
      start: 0.077,
      name: "Descente de la Chapelle",
    },
    {
      start: 0.087,
      name: "S du Tetre Rouge",
    },
    {
      start: 0.133,
      name: "Virage du Tertre Rouge",
    },
    {
      start: 0.182,
      name: "Courbe d'Antares",
    },
    {
      start: 0.468,
      name: "Courbe des Hunaudieres",
    },
    {
      start: 0.55,
      name: "Virage de Mulsanne",
    },
    {
      start: 0.61,
      name: "Courbe du Golf",
    },
    {
      start: 0.695,
      name: "Esses d'Indianapolis",
    },
    {
      start: 0.74,
      name: "Virage d'Arnage",
    },
    {
      start: 0.77,
      name: "Courbe du Buisson",
    },
    {
      start: 0.829,
      name: "Virage Porsche",
    },
    {
      start: 0.856,
      name: "Virage du Pont",
    },
    {
      start: 0.877,
      name: "Esses du Karting",
    },
    {
      start: 0.907,
      name: "Virage Corvette",
    },
    {
      start: 0.933,
      name: "Maison Blanche",
    },
    {
      start: 0.968,
      name: "Virage Ford",
    },
    {
      start: 0.98,
      name: "Virage du Raccordement",
    },
  ],
  "limerock 2019 classic": [
    {
      start: 0.077,
      name: "Big Bend",
    },
    {
      start: 0.234,
      name: "Esses",
    },
    {
      start: 0.48,
      name: "Uphill",
    },
    {
      start: 0.649,
      name: "West Bend",
    },
    {
      start: 0.788,
      name: "Diving Turn",
    },
  ],
  "limerock 2019 gp": [
    {
      start: 0.077,
      name: "Big Bend",
    },
    {
      start: 0.234,
      name: "Esses",
    },
    {
      start: 0.48,
      name: "Uphill",
    },
    {
      start: 0.649,
      name: "West Bend",
    },
    {
      start: 0.788,
      name: "Diving Turn",
    },
  ],
  longbeach: [
    {
      start: 0.223,
      name: "Turn 1",
    },
    {
      start: 0.283,
      name: "Turn 2",
    },
    {
      start: 0.295,
      name: "Turn 3",
    },
    {
      start: 0.331,
      name: "Turn 4",
    },
    {
      start: 0.378,
      name: "Turn 5",
    },
    {
      start: 0.505,
      name: "Turn 6",
    },
    {
      start: 0.536,
      name: "Turn 7",
    },
    {
      start: 0.602,
      name: "Turn 8",
    },
    {
      start: 0.801,
      name: "Turn 9",
    },
    {
      start: 0.842,
      name: "Turn 10",
    },
    {
      start: 0.882,
      name: "Turn 11",
    },
  ],
  "magnycours gp": [
    {
      start: 0.074,
      name: "Grande Courbe",
    },
    {
      start: 0.129,
      name: "Estoril",
    },
    {
      start: 0.285,
      name: "Golf",
    },
    {
      start: 0.395,
      name: "Adelaide",
    },
    {
      start: 0.51,
      name: "Nuerburgring",
    },
    {
      start: 0.59,
      name: "180°",
    },
    {
      start: 0.735,
      name: "Imola",
    },
    {
      start: 0.805,
      name: "Chateaou d'Eau",
    },
    {
      start: 0.88,
      name: "Chicane",
    },
    {
      start: 0.94,
      name: "Complexe du Lycee",
    },
  ],
  "misano gp": [
    {
      start: 0.049,
      name: "Variante del Parco",
    },
    {
      start: 0.17,
      name: "Curva del Rio",
    },
    {
      start: 0.365,
      name: "Curva Quericia",
    },
    {
      start: 0.475,
      name: "Curva Tramonto",
    },
    {
      start: 0.645,
      name: "Curvone",
    },
    {
      start: 0.79,
      name: "Curva del Carro",
    },
    {
      start: 0.84,
      name: "Turn 15",
    },
    {
      start: 0.9,
      name: "Curva Misano",
    },
  ],
  montreal: [
    {
      start: 0.037,
      name: "Virage Senna",
    },
    {
      start: 0.145,
      name: "T3/T4",
    },
    {
      start: 0.206,
      name: "Turn 5",
    },
    {
      start: 0.273,
      name: "T6/T7",
    },
    {
      start: 0.44,
      name: "T8/T9",
    },
    {
      start: 0.595,
      name: "L'Epingle",
    },
    {
      start: 0.635,
      name: "Turn 11",
    },
    {
      start: 0.71,
      name: "Turn 12",
    },
    {
      start: 0.878,
      name: "Turn 13",
    },
    {
      start: 0.9,
      name: "T14 - Wall of Champions",
    },
  ],
  "monza full": [
    {
      start: 0.143,
      name: "Prima Variante",
    },
    {
      start: 0.218,
      name: "Curva Biassono",
    },
    {
      start: 0.35,
      name: "Seconda Variante",
    },
    {
      start: 0.423,
      name: "Prima Curva di Lesmo",
    },
    {
      start: 0.484,
      name: "Seconda Curva di Lesmo",
    },
    {
      start: 0.555,
      name: "Curva del Serraglio",
    },
    {
      start: 0.65,
      name: "Variante Ascari",
    },
    {
      start: 0.866,
      name: "Curva Parabolica",
    },
  ],
  "mugello gp": [
    {
      start: 0.116,
      name: "San Donato",
    },
    {
      start: 0.17,
      name: "Luco",
    },
    {
      start: 0.195,
      name: "Poggiosecco",
    },
    {
      start: 0.268,
      name: "Materassi",
    },
    {
      start: 0.295,
      name: "Borgo San Lorenzo",
    },
    {
      start: 0.355,
      name: "Casanova",
    },
    {
      start: 0.39,
      name: "Savelli",
    },
    {
      start: 0.436,
      name: "Arrabbiata 1",
    },
    {
      start: 0.495,
      name: "Arrabbiata 2",
    },
    {
      start: 0.57,
      name: "Scarperia",
    },
    {
      start: 0.592,
      name: "Palagio",
    },
    {
      start: 0.666,
      name: "Correntaio",
    },
    {
      start: 0.73,
      name: "Biondetti 1",
    },
    {
      start: 0.755,
      name: "Biondetti 2",
    },
    {
      start: 0.83,
      name: "Bucine",
    },
  ],
  "navarra speedlong": [
    {
      start: 0.089,
      name: "Turn 1",
    },
    {
      start: 0.126,
      name: "Turn 2",
    },
    {
      start: 0.161,
      name: "Turn 3",
    },
    {
      start: 0.202,
      name: "Turn 4",
    },
    {
      start: 0.29,
      name: "Turn 5",
    },
    {
      start: 0.346,
      name: "Turn 6",
    },
    {
      start: 0.386,
      name: "Turn 7",
    },
    {
      start: 0.435,
      name: "Turn 8",
    },
    {
      start: 0.565,
      name: "Turn 9",
    },
    {
      start: 0.606,
      name: "Turn 10",
    },
    {
      start: 0.646,
      name: "Turn 11",
    },
    {
      start: 0.69,
      name: "Turn 12",
    },
    {
      start: 0.75,
      name: "Turn 13",
    },
    {
      start: 0.815,
      name: "Turn 14",
    },
    {
      start: 0.868,
      name: "Turn 15",
    },
  ],
  "nurburgring combined": [
    {
      start: 0.021,
      name: "Yokohama-S",
    },
    {
      start: 0.042,
      name: "Valvoline Kurve",
    },
    {
      start: 0.051,
      name: "Ford-Kurve",
    },
    {
      start: 0.071,
      name: "Dunlop-Kehre",
    },
    {
      start: 0.087,
      name: "Michael-Schumacher-S",
    },
    {
      start: 0.11,
      name: "Michelin-Kurve",
    },
    {
      start: 0.118,
      name: "Warsteiner-Kurve",
    },
    {
      start: 0.135,
      name: "ADVAN-Bogen",
    },
    {
      start: 0.153,
      name: "NGK-Schikane",
    },
    {
      start: 0.165,
      name: "Turn 13",
    },
    {
      start: 0.183,
      name: "Hatzenbach",
    },
    {
      start: 0.226,
      name: "Hoheneichen",
    },
    {
      start: 0.251,
      name: "Quiddelbacher Hoehe",
    },
    {
      start: 0.252,
      name: "Flugplatz",
    },
    {
      start: 0.304,
      name: "Schwedenkreuz",
    },
    {
      start: 0.317,
      name: "Aremberg",
    },
    {
      start: 0.342,
      name: "Fuchsroehre",
    },
    {
      start: 0.368,
      name: "Adenauer Forst",
    },
    {
      start: 0.398,
      name: "Metzgesfeld",
    },
    {
      start: 0.417,
      name: "Kallenhard",
    },
    {
      start: 0.43,
      name: "Spiegelkurve",
    },
    {
      start: 0.438,
      name: "Dreifach-Rechts",
    },
    {
      start: 0.455,
      name: "Wehrseifen",
    },
    {
      start: 0.487,
      name: "ExMuehle",
    },
    {
      start: 0.514,
      name: "Bergwerk",
    },
    {
      start: 0.56,
      name: "Kesselchen",
    },
    {
      start: 0.576,
      name: "Klostertal",
    },
    {
      start: 0.587,
      name: "Mutkurve",
    },
    {
      start: 0.639,
      name: "Caracciola-Karussell",
    },
    {
      start: 0.675,
      name: "Hohe Acht",
    },
    {
      start: 0.686,
      name: "Hedwigshoehe",
    },
    {
      start: 0.703,
      name: "Wippermann",
    },
    {
      start: 0.717,
      name: "Eschbach",
    },
    {
      start: 0.731,
      name: "Bruennchen",
    },
    {
      start: 0.761,
      name: "Pflanzgarten",
    },
    {
      start: 0.799,
      name: "Stefan-Bellof-S",
    },
    {
      start: 0.821,
      name: "Schwalbenschwanz",
    },
    {
      start: 0.848,
      name: "Galgenkopf",
    },
    {
      start: 0.866,
      name: "Doettinger Hoehe",
    },
    {
      start: 0.94,
      name: "Antoniusbuche",
    },
    {
      start: 0.959,
      name: "Tiergarten",
    },
    {
      start: 0.966,
      name: "Hohenrain",
    },
  ],
  "nurburgring nordschleife": [
    {
      start: 0.02,
      name: "Hatzenbach",
    },
    {
      start: 0.072,
      name: "Hoheneichen",
    },
    {
      start: 0.09,
      name: "Quiddelbacher Hoehe",
    },
    {
      start: 0.11,
      name: "Flugplatz",
    },
    {
      start: 0.167,
      name: "Schwedenkreuz",
    },
    {
      start: 0.18,
      name: "Aremberg",
    },
    {
      start: 0.198,
      name: "Fuchsroehre",
    },
    {
      start: 0.235,
      name: "Adenauer Forst",
    },
    {
      start: 0.269,
      name: "Metzgesfeld",
    },
    {
      start: 0.302,
      name: "Kallenhard",
    },
    {
      start: 0.321,
      name: "Spiegelkurve",
    },
    {
      start: 0.33,
      name: "Dreifach-Rechts",
    },
    {
      start: 0.356,
      name: "Wehrseifen",
    },
    {
      start: 0.371,
      name: "ExMuehle",
    },
    {
      start: 0.42,
      name: "Bergwerk",
    },
    {
      start: 0.451,
      name: "Kesselchen",
    },
    {
      start: 0.515,
      name: "Mutkurve",
    },
    {
      start: 0.528,
      name: "Klostertal",
    },
    {
      start: 0.576,
      name: "Caracciola-Karussell",
    },
    {
      start: 0.616,
      name: "Hohe Acht",
    },
    {
      start: 0.633,
      name: "Hedwigshoehe",
    },
    {
      start: 0.653,
      name: "Wippermann",
    },
    {
      start: 0.669,
      name: "Eschbach",
    },
    {
      start: 0.688,
      name: "Bruennchen",
    },
    {
      start: 0.729,
      name: "Pflanzgarten",
    },
    {
      start: 0.772,
      name: "Stefan-Bellof-S",
    },
    {
      start: 0.792,
      name: "Schwalbenschwanz",
    },
    {
      start: 0.832,
      name: "Galgenkopf",
    },
    {
      start: 0.855,
      name: "Doettinger Hoehe",
    },
    {
      start: 0.945,
      name: "Antoniusbuche",
    },
    {
      start: 0.962,
      name: "Tiergarten",
    },
    {
      start: 0.973,
      name: "Tiergarten",
    },
  ],
  "okayama full": [
    {
      start: 0.038,
      name: "First Corner",
    },
    {
      start: 0.115,
      name: "Williams",
    },
    {
      start: 0.19,
      name: "Moss S",
    },
    {
      start: 0.28,
      name: "Attwood Curve",
    },
    {
      start: 0.525,
      name: "Hairpin Corner",
    },
    {
      start: 0.585,
      name: "Revolver Corner",
    },
    {
      start: 0.622,
      name: "Piper Corner",
    },
    {
      start: 0.705,
      name: "Redman Corner",
    },
    {
      start: 0.755,
      name: "Hobbs Corner",
    },
    {
      start: 0.82,
      name: "Mike Knight Corner",
    },
    {
      start: 0.859,
      name: "Last Corner",
    },
  ],
  "oran gp": [
    {
      start: 0.147,
      name: "The Sweeper",
    },
    {
      start: 0.196,
      name: "Coca-Cola Corner",
    },
    {
      start: 0.32,
      name: "Shell Corner",
    },
    {
      start: 0.414,
      name: "Champion Curve",
    },
    {
      start: 0.478,
      name: "Yokohama Bridge",
    },
    {
      start: 0.575,
      name: "Foster's Dip",
    },
    {
      start: 0.67,
      name: "Momo Corner",
    },
    {
      start: 0.755,
      name: "O'Brien Aluminium Dogleg",
    },
    {
      start: 0.85,
      name: "Recaro Corner",
    },
  ],
  "oschersleben alt": [
    {
      start: 0.139,
      name: "Hotel",
    },
    {
      start: 0.25,
      name: "Hasseroeder",
    },
    {
      start: 0.416,
      name: "Triple",
    },
    {
      start: 0.578,
      name: "McDonald's",
    },
    {
      start: 0.73,
      name: "Shell Kurve",
    },
    {
      start: 0.771,
      name: "Amman Kurve",
    },
    {
      start: 0.841,
      name: "Bauer Kurve",
    },
    {
      start: 0.895,
      name: "Zeppelin Kurve",
    },
  ],
  "oschersleben bcourse": [
    {
      start: 0.208,
      name: "Hotel",
    },
    {
      start: 0.387,
      name: "Hasseröder",
    },
    {
      start: 0.604,
      name: "Shell Kurve",
    },
    {
      start: 0.659,
      name: "Amman Kurve",
    },
    {
      start: 0.766,
      name: "Bauer Kurve",
    },
    {
      start: 0.841,
      name: "Zeppelin Kurve",
    },
  ],
  "oschersleben gp": [
    {
      start: 0.1,
      name: "Hotel",
    },
    {
      start: 0.25,
      name: "Hasseroeder",
    },
    {
      start: 0.375,
      name: "Triple",
    },
    {
      start: 0.463,
      name: "Turn 7",
    },
    {
      start: 0.544,
      name: "Schikane",
    },
    {
      start: 0.578,
      name: "McDonald's",
    },
    {
      start: 0.73,
      name: "Shell Kurve",
    },
    {
      start: 0.771,
      name: "Amman Kurve",
    },
    {
      start: 0.841,
      name: "Bauer Kurve",
    },
    {
      start: 0.895,
      name: "Zeppelin Kurve",
    },
  ],
  "oulton international": [
    {
      start: 0.043,
      name: "Old Hall Corner",
    },
    {
      start: 0.137,
      name: "Denton's",
    },
    {
      start: 0.162,
      name: "Cascades",
    },
    {
      start: 0.303,
      name: "Island Bend",
    },
    {
      start: 0.365,
      name: "Shell Oils Corner",
    },
    {
      start: 0.464,
      name: "Britten's",
    },
    {
      start: 0.592,
      name: "Hislop's",
    },
    {
      start: 0.635,
      name: "Knickerbrook",
    },
    {
      start: 0.686,
      name: "Clay Hill",
    },
    {
      start: 0.746,
      name: "Water Tower",
    },
    {
      start: 0.78,
      name: "Druids Corner",
    },
    {
      start: 0.903,
      name: "Lodge Corner",
    },
    {
      start: 0.956,
      name: "Deer Leap",
    },
  ],
  "oulton inthislop": [
    {
      start: 0.043,
      name: "Old Hall Corner",
    },
    {
      start: 0.137,
      name: "Denton's",
    },
    {
      start: 0.162,
      name: "Cascades",
    },
    {
      start: 0.303,
      name: "Island Bend",
    },
    {
      start: 0.365,
      name: "Shell Oils Corner",
    },
    {
      start: 0.592,
      name: "Hislop's",
    },
    {
      start: 0.635,
      name: "Knickerbrook",
    },
    {
      start: 0.686,
      name: "Clay Hill",
    },
    {
      start: 0.746,
      name: "Water Tower",
    },
    {
      start: 0.781,
      name: "Druids Corner",
    },
    {
      start: 0.903,
      name: "Lodge Corner",
    },
    {
      start: 0.956,
      name: "Deer Leap",
    },
  ],
  "roadamerica bend": [
    {
      start: 0.079,
      name: "Turn 1",
    },
    {
      start: 0.153,
      name: "Turn 3",
    },
    {
      start: 0.252,
      name: "Moraine Sweep",
    },
    {
      start: 0.331,
      name: "Turn 5",
    },
    {
      start: 0.386,
      name: "Turn 6",
    },
    {
      start: 0.425,
      name: "Turn 7",
    },
    {
      start: 0.479,
      name: "Turn 8",
    },
    {
      start: 0.524,
      name: "The Carousel",
    },
    {
      start: 0.624,
      name: "The Bend",
    },
    {
      start: 0.713,
      name: "Kettle Bottoms",
    },
    {
      start: 0.777,
      name: "Canada Corner",
    },
    {
      start: 0.826,
      name: "Bill Mitchell Bend",
    },
    {
      start: 0.872,
      name: "Turn 14",
    },
  ],
  "roadamerica full": [
    {
      start: 0.08,
      name: "Turn 1",
    },
    {
      start: 0.155,
      name: "Turn 3",
    },
    {
      start: 0.255,
      name: "Moraine Sweep",
    },
    {
      start: 0.335,
      name: "Turn 5",
    },
    {
      start: 0.39,
      name: "Turn 6",
    },
    {
      start: 0.43,
      name: "Turn 7",
    },
    {
      start: 0.484,
      name: "Turn 8",
    },
    {
      start: 0.53,
      name: "The Carousel",
    },
    {
      start: 0.64,
      name: "The Kink",
    },
    {
      start: 0.71,
      name: "Kettle Bottoms",
    },
    {
      start: 0.775,
      name: "Canada Corner",
    },
    {
      start: 0.824,
      name: "Bill Mitchell Bend",
    },
    {
      start: 0.871,
      name: "Turn 14",
    },
  ],
  "roadatlanta full": [
    {
      start: 0.049,
      name: "Turn 1",
    },
    {
      start: 0.156,
      name: "Turn 2",
    },
    {
      start: 0.196,
      name: "Turn 3",
    },
    {
      start: 0.214,
      name: "Turn 4",
    },
    {
      start: 0.26,
      name: "The Esses",
    },
    {
      start: 0.333,
      name: "Turn 5",
    },
    {
      start: 0.466,
      name: "Turn 6",
    },
    {
      start: 0.515,
      name: "Turn 7",
    },
    {
      start: 0.56,
      name: "Turn 8",
    },
    {
      start: 0.729,
      name: "Turn 9",
    },
    {
      start: 0.825,
      name: "Turn 10A",
    },
    {
      start: 0.867,
      name: "Turn 10B",
    },
    {
      start: 0.908,
      name: "Turn 11",
    },
    {
      start: 0.959,
      name: "Turn 12",
    },
  ],
  rudskogen: [
    {
      start: 0.092,
      name: "Turn 1",
    },
    {
      start: 0.132,
      name: "Turn 2",
    },
    {
      start: 0.324,
      name: "Turn 3",
    },
    {
      start: 0.408,
      name: "Turn 4",
    },
    {
      start: 0.47,
      name: "Turn 5",
    },
    {
      start: 0.5,
      name: "Turn 6",
    },
    {
      start: 0.528,
      name: "Turn 7",
    },
    {
      start: 0.553,
      name: "Turn 8",
    },
    {
      start: 0.599,
      name: "Turn 9",
    },
    {
      start: 0.671,
      name: "Turn 10",
    },
    {
      start: 0.739,
      name: "Turn 11",
    },
    {
      start: 0.775,
      name: "Turn 12",
    },
    {
      start: 0.82,
      name: "Turn 13",
    },
    {
      start: 0.855,
      name: "Turn 14",
    },
  ],
  sachsenring: [
    {
      start: 0.129,
      name: "auto motor und sport-Kurve",
    },
    {
      start: 0.19,
      name: "Omega-Kurve",
    },
    {
      start: 0.308,
      name: "Kleine Kuppe-Kurve",
    },
    {
      start: 0.41,
      name: "Karthallen-Kurve",
    },
    {
      start: 0.51,
      name: "Volkswagen-Kurve",
    },
    {
      start: 0.58,
      name: "Grosse Kuppe-Kurve",
    },
    {
      start: 0.62,
      name: "Nordkurve",
    },
    {
      start: 0.668,
      name: "Ralf-Waldmann-Kurve",
    },
    {
      start: 0.797,
      name: "Sachsen Kurve",
    },
    {
      start: 0.915,
      name: "Queckenberg Kurve",
    },
  ],
  "sebring international": [
    {
      start: 0.053,
      name: "Turn One",
    },
    {
      start: 0.125,
      name: "Turn Two",
    },
    {
      start: 0.152,
      name: "Turn 3",
    },
    {
      start: 0.171,
      name: "Turn 4",
    },
    {
      start: 0.186,
      name: "Turn 5",
    },
    {
      start: 0.214,
      name: "Gurney Bend",
    },
    {
      start: 0.329,
      name: "Hairpin Turn",
    },
    {
      start: 0.374,
      name: "Fangio Chicane",
    },
    {
      start: 0.403,
      name: "Fangio Chicane",
    },
    {
      start: 0.466,
      name: "Cunningham",
    },
    {
      start: 0.493,
      name: "Turn 11",
    },
    {
      start: 0.53,
      name: "Turn 12",
    },
    {
      start: 0.552,
      name: "Tower Turn",
    },
    {
      start: 0.62,
      name: "Bishop Bend",
    },
    {
      start: 0.68,
      name: "Gendebien Bend",
    },
    {
      start: 0.712,
      name: "Le Mans Curve",
    },
    {
      start: 0.881,
      name: "Sunset Bend",
    },
  ],
  "silverstone 2019 gp": [
    {
      start: 0.05,
      name: "Abbey",
    },
    {
      start: 0.092,
      name: "Farm Curve",
    },
    {
      start: 0.141,
      name: "Village",
    },
    {
      start: 0.168,
      name: "The Loop",
    },
    {
      start: 0.195,
      name: "Aintree",
    },
    {
      start: 0.313,
      name: "Brooklands",
    },
    {
      start: 0.353,
      name: "Luffield",
    },
    {
      start: 0.407,
      name: "Woodcote",
    },
    {
      start: 0.5,
      name: "Copse",
    },
    {
      start: 0.604,
      name: "Maggots",
    },
    {
      start: 0.644,
      name: "Becketts",
    },
    {
      start: 0.672,
      name: "Chapel",
    },
    {
      start: 0.836,
      name: "Stowe",
    },
    {
      start: 0.924,
      name: "Vale",
    },
    {
      start: 0.948,
      name: "Club",
    },
  ],
  "snetterton 300": [
    {
      start: 0.049,
      name: "Riches",
    },
    {
      start: 0.15,
      name: "Wilson",
    },
    {
      start: 0.221,
      name: "Palmer",
    },
    {
      start: 0.325,
      name: "Agostini",
    },
    {
      start: 0.404,
      name: "Hamilton",
    },
    {
      start: 0.456,
      name: "Oggies",
    },
    {
      start: 0.504,
      name: "Williams",
    },
    {
      start: 0.675,
      name: "Brundle",
    },
    {
      start: 0.755,
      name: "Bomb Hole",
    },
    {
      start: 0.808,
      name: "Coram",
    },
    {
      start: 0.891,
      name: "Murrays",
    },
  ],
  "spa 2024 combined": [
    {
      start: 0.046,
      name: "La Source",
    },
    {
      start: 0.138,
      name: "Eau Rouge",
    },
    {
      start: 0.156,
      name: "Raidillon",
    },
    {
      start: 0.216,
      name: "Kemmel",
    },
    {
      start: 0.328,
      name: "Les Combes",
    },
    {
      start: 0.371,
      name: "Malmedy",
    },
    {
      start: 0.42,
      name: "Bruxelles",
    },
    {
      start: 0.462,
      name: "Speaker's Corner",
    },
    {
      start: 0.532,
      name: "Double Gauche",
    },
    {
      start: 0.63,
      name: "Les Fagnes",
    },
    {
      start: 0.693,
      name: "Campus",
    },
    {
      start: 0.727,
      name: "Stavelot",
    },
    {
      start: 0.766,
      name: "Courbe Paul Frere",
    },
    {
      start: 0.869,
      name: "Blanchimont",
    },
    {
      start: 0.953,
      name: "Chicane",
    },
  ],
  "spa 2024 low": [
    {
      start: 0.024,
      name: "Eau Rouge",
    },
    {
      start: 0.043,
      name: "Raidillon",
    },
    {
      start: 0.103,
      name: "Kemmel",
    },
    {
      start: 0.211,
      name: "Les Combes",
    },
    {
      start: 0.256,
      name: "Malmedy",
    },
    {
      start: 0.3,
      name: "Bruxelles",
    },
    {
      start: 0.343,
      name: "Speaker's Corner",
    },
    {
      start: 0.415,
      name: "Double Gauche",
    },
    {
      start: 0.51,
      name: "Les Fagnes",
    },
    {
      start: 0.579,
      name: "Campus",
    },
    {
      start: 0.611,
      name: "Stavelot",
    },
    {
      start: 0.661,
      name: "Courbe Paul Frere",
    },
    {
      start: 0.755,
      name: "Blanchimont",
    },
    {
      start: 0.835,
      name: "Chicane",
    },
    {
      start: 0.93,
      name: "La Source",
    },
  ],
  "spa 2024 up": [
    {
      start: 0.046,
      name: "La Source",
    },
    {
      start: 0.138,
      name: "Eau Rouge",
    },
    {
      start: 0.156,
      name: "Raidillon",
    },
    {
      start: 0.216,
      name: "Kemmel",
    },
    {
      start: 0.328,
      name: "Les Combes",
    },
    {
      start: 0.371,
      name: "Malmedy",
    },
    {
      start: 0.42,
      name: "Bruxelles",
    },
    {
      start: 0.462,
      name: "Speaker's Corner",
    },
    {
      start: 0.532,
      name: "Double Gauche",
    },
    {
      start: 0.63,
      name: "Les Fagnes",
    },
    {
      start: 0.693,
      name: "Campus",
    },
    {
      start: 0.727,
      name: "Stavelot",
    },
    {
      start: 0.766,
      name: "Courbe Paul Frere",
    },
    {
      start: 0.869,
      name: "Blanchimont",
    },
    {
      start: 0.953,
      name: "Chicane",
    },
  ],
  "spa combined": [
    {
      start: 0.046,
      name: "La Source",
    },
    {
      start: 0.138,
      name: "Eau Rouge",
    },
    {
      start: 0.156,
      name: "Raidillon",
    },
    {
      start: 0.216,
      name: "Kemmel",
    },
    {
      start: 0.328,
      name: "Les Combes",
    },
    {
      start: 0.371,
      name: "Malmedy",
    },
    {
      start: 0.42,
      name: "Bruxelles",
    },
    {
      start: 0.462,
      name: "Speaker's Corner",
    },
    {
      start: 0.532,
      name: "Double Gauche",
    },
    {
      start: 0.63,
      name: "Les Fagnes",
    },
    {
      start: 0.693,
      name: "Campus",
    },
    {
      start: 0.727,
      name: "Stavelot",
    },
    {
      start: 0.766,
      name: "Courbe Paul Frere",
    },
    {
      start: 0.869,
      name: "Blanchimont",
    },
    {
      start: 0.953,
      name: "Chicane",
    },
  ],
  "spa low": [
    {
      start: 0.024,
      name: "Eau Rouge",
    },
    {
      start: 0.043,
      name: "Raidillon",
    },
    {
      start: 0.103,
      name: "Kemmel",
    },
    {
      start: 0.211,
      name: "Les Combes",
    },
    {
      start: 0.256,
      name: "Malmedy",
    },
    {
      start: 0.3,
      name: "Bruxelles",
    },
    {
      start: 0.343,
      name: "Speaker's Corner",
    },
    {
      start: 0.415,
      name: "Double Gauche",
    },
    {
      start: 0.51,
      name: "Les Fagnes",
    },
    {
      start: 0.579,
      name: "Campus",
    },
    {
      start: 0.611,
      name: "Stavelot",
    },
    {
      start: 0.661,
      name: "Courbe Paul Frere",
    },
    {
      start: 0.755,
      name: "Blanchimont",
    },
    {
      start: 0.835,
      name: "Chicane",
    },
    {
      start: 0.93,
      name: "La Source",
    },
  ],
  "spa up": [
    {
      start: 0.046,
      name: "La Source",
    },
    {
      start: 0.138,
      name: "Eau Rouge",
    },
    {
      start: 0.156,
      name: "Raidillon",
    },
    {
      start: 0.216,
      name: "Kemmel",
    },
    {
      start: 0.328,
      name: "Les Combes",
    },
    {
      start: 0.371,
      name: "Malmedy",
    },
    {
      start: 0.42,
      name: "Bruxelles",
    },
    {
      start: 0.462,
      name: "Speaker's Corner",
    },
    {
      start: 0.532,
      name: "Double Gauche",
    },
    {
      start: 0.63,
      name: "Les Fagnes",
    },
    {
      start: 0.693,
      name: "Campus",
    },
    {
      start: 0.727,
      name: "Stavelot",
    },
    {
      start: 0.766,
      name: "Courbe Paul Frere",
    },
    {
      start: 0.869,
      name: "Blanchimont",
    },
    {
      start: 0.953,
      name: "Chicane",
    },
  ],
  "spielberg gp": [
    {
      start: 0.075,
      name: "Niki Lauda Kurve",
    },
    {
      start: 0.29,
      name: "Remus",
    },
    {
      start: 0.47,
      name: "Schlossgold",
    },
    {
      start: 0.59,
      name: "Rauch",
    },
    {
      start: 0.675,
      name: "Wuerth",
    },
    {
      start: 0.83,
      name: "Rindt",
    },
    {
      start: 0.905,
      name: "Red Bull Mobile",
    },
  ],
  "summit summit raceway": [
    {
      start: 0.141,
      name: "Turn 1",
    },
    {
      start: 0.307,
      name: "Wagon Bend",
    },
    {
      start: 0.455,
      name: "Chute",
    },
    {
      start: 0.51,
      name: "Carousel",
    },
    {
      start: 0.628,
      name: "Esses",
    },
    {
      start: 0.84,
      name: "Paddock Bend",
    },
  ],
  "suzuka grandprix": [
    {
      start: 0.104,
      name: "First Corner",
    },
    {
      start: 0.18,
      name: "Snake",
    },
    {
      start: 0.254,
      name: "Anti-Banked Curve",
    },
    {
      start: 0.29,
      name: "Dunlop",
    },
    {
      start: 0.385,
      name: "Degner",
    },
    {
      start: 0.49,
      name: "Hairpin",
    },
    {
      start: 0.54,
      name: "200R",
    },
    {
      start: 0.645,
      name: "Spoon Curve",
    },
    {
      start: 0.841,
      name: "130R",
    },
    {
      start: 0.915,
      name: "Casio Triangle",
    },
    {
      start: 0.949,
      name: "Last Curve",
    },
  ],
  "virginia 2022 full": [
    {
      start: 0.049,
      name: "Turn 18",
    },
    {
      start: 0.05,
      name: "Horseshoe",
    },
    {
      start: 0.12,
      name: "Turn 2",
    },
    {
      start: 0.149,
      name: "Nascar Bend",
    },
    {
      start: 0.181,
      name: "Left Hook",
    },
    {
      start: 0.207,
      name: "Turn 4b",
    },
    {
      start: 0.226,
      name: "Turn 5a",
    },
    {
      start: 0.244,
      name: "Snake",
    },
    {
      start: 0.347,
      name: "Turn 7",
    },
    {
      start: 0.368,
      name: "Turn 8a",
    },
    {
      start: 0.387,
      name: "Turn 8b",
    },
    {
      start: 0.405,
      name: "Turn 9",
    },
    {
      start: 0.44,
      name: "South Bend",
    },
    {
      start: 0.502,
      name: "Oak Tree",
    },
    {
      start: 0.748,
      name: "Roller Coaster",
    },
    {
      start: 0.831,
      name: "Hog Pen",
    },
  ],
  "virginia 2022 grand": [
    {
      start: 0.051,
      name: "Horseshoe",
    },
    {
      start: 0.12,
      name: "Nascar Bend",
    },
    {
      start: 0.151,
      name: "Left Hook",
    },
    {
      start: 0.165,
      name: "T4b",
    },
    {
      start: 0.182,
      name: "T5a",
    },
    {
      start: 0.193,
      name: "T5b",
    },
    {
      start: 0.205,
      name: "Snake",
    },
    {
      start: 0.213,
      name: "T6b",
    },
    {
      start: 0.276,
      name: "Turn 7",
    },
    {
      start: 0.294,
      name: "T8a",
    },
    {
      start: 0.309,
      name: "T8b",
    },
    {
      start: 0.325,
      name: "Turn 9",
    },
    {
      start: 0.358,
      name: "South Bend",
    },
    {
      start: 0.407,
      name: "Turn 11",
    },
    {
      start: 0.42,
      name: "Oak Tree",
    },
    {
      start: 0.561,
      name: "Bitch",
    },
    {
      start: 0.607,
      name: "Turn 14",
    },
    {
      start: 0.63,
      name: "T15a",
    },
    {
      start: 0.645,
      name: "T15b",
    },
    {
      start: 0.653,
      name: "Turn 16",
    },
    {
      start: 0.699,
      name: "T17a",
    },
    {
      start: 0.706,
      name: "T17b",
    },
    {
      start: 0.714,
      name: "T17c",
    },
    {
      start: 0.724,
      name: "T17d",
    },
    {
      start: 0.75,
      name: "T18a",
    },
    {
      start: 0.765,
      name: "T18b",
    },
    {
      start: 0.782,
      name: "T19a",
    },
    {
      start: 0.783,
      name: "T19b",
    },
    {
      start: 0.825,
      name: "Roller Coaster",
    },
    {
      start: 0.841,
      name: "Turn 21",
    },
    {
      start: 0.87,
      name: "T22a",
    },
    {
      start: 0.884,
      name: "T22b",
    },
    {
      start: 0.9,
      name: "Turn 23",
    },
    {
      start: 0.97,
      name: "Turn 24",
    },
  ],
  "virginia 2022 north": [
    {
      start: 0.1,
      name: "Horseshoe",
    },
    {
      start: 0.19,
      name: "Turn 2",
    },
    {
      start: 0.22,
      name: "Nascar Bend",
    },
    {
      start: 0.265,
      name: "Left Hook",
    },
    {
      start: 0.296,
      name: "Turn 4b",
    },
    {
      start: 0.33,
      name: "Turn 5a",
    },
    {
      start: 0.351,
      name: "Turn 5b",
    },
    {
      start: 0.371,
      name: "Snake",
    },
    {
      start: 0.385,
      name: "Turn 6b",
    },
    {
      start: 0.48,
      name: "Turn 7",
    },
    {
      start: 0.52,
      name: "Turn 8a",
    },
    {
      start: 0.541,
      name: "Turn 8b",
    },
    {
      start: 0.57,
      name: "Turn 9a",
    },
    {
      start: 0.61,
      name: "Turn 9b",
    },
    {
      start: 0.646,
      name: "Turn 9c",
    },
    {
      start: 0.683,
      name: "Roller Coaster",
    },
    {
      start: 0.711,
      name: "Turn 11",
    },
    {
      start: 0.76,
      name: "Turn 12a",
    },
    {
      start: 0.787,
      name: "Turn 12b",
    },
    {
      start: 0.825,
      name: "Turn 13",
    },
    {
      start: 0.95,
      name: "Turn 14",
    },
  ],
  "virginia 2022 patriot": [
    {
      start: 0.59,
      name: "Spiral",
    },
  ],
  "virginia 2022 south": [
    {
      start: 0.233,
      name: "Bitch",
    },
    {
      start: 0.441,
      name: "Spiral",
    },
    {
      start: 0.565,
      name: "Fish Hook",
    },
    {
      start: 0.704,
      name: "South Bend",
    },
    {
      start: 0.869,
      name: "Oak Tree",
    },
  ],
  "watkinsglen 2021 fullcourse": [
    {
      start: 0.045,
      name: "The 90",
    },
    {
      start: 0.113,
      name: "Esses",
    },
    {
      start: 0.341,
      name: "Inner Loop",
    },
    {
      start: 0.392,
      name: "Outer Loop",
    },
    {
      start: 0.49,
      name: "Chute",
    },
    {
      start: 0.58,
      name: "Toe",
    },
    {
      start: 0.718,
      name: "Heel",
    },
    {
      start: 0.781,
      name: "Turn 9",
    },
    {
      start: 0.844,
      name: "Turn 10",
    },
    {
      start: 0.913,
      name: "Turn 11",
    },
  ],
  "winton club": [
    {
      start: 0.061,
      name: "Honda Corner",
    },
    {
      start: 0.117,
      name: "Nissan Corner",
    },
    {
      start: 0.389,
      name: "Roll-Over Corner",
    },
    {
      start: 0.441,
      name: "Penrite Corner",
    },
    {
      start: 0.591,
      name: "Kitome Corner",
    },
  ],
  "winton national": [
    {
      start: 0.063,
      name: "Motorsport News Esses",
    },
    {
      start: 0.195,
      name: "Honda Corner",
    },
    {
      start: 0.245,
      name: "Nissan Corner",
    },
    {
      start: 0.321,
      name: "Turn 5",
    },
    {
      start: 0.426,
      name: "Roll-Over Corner",
    },
    {
      start: 0.46,
      name: "Penrite Corner",
    },
    {
      start: 0.505,
      name: "Turn 8",
    },
    {
      start: 0.558,
      name: "Kitome Corner",
    },
    {
      start: 0.683,
      name: "Northern BM Corner",
    },
    {
      start: 0.829,
      name: "Advanced Petroleum Corner",
    },
  ],
  "zandvoort 2023 gp": [
    {
      start: 0.05,
      name: "Tarzanbocht",
    },
    {
      start: 0.129,
      name: "Gerlachbocht",
    },
    {
      start: 0.175,
      name: "Hugenholzbocht",
    },
    {
      start: 0.305,
      name: "Rob Slotemakerbocht",
    },
    {
      start: 0.37,
      name: "Scheivlak",
    },
    {
      start: 0.46,
      name: "Mastersbocht",
    },
    {
      start: 0.523,
      name: "Bocht 9",
    },
    {
      start: 0.556,
      name: "Bocht 10",
    },
    {
      start: 0.706,
      name: "Hans Ernst Bocht",
    },
    {
      start: 0.8,
      name: "Kumho",
    },
    {
      start: 0.85,
      name: "Arie Luyendijk Bocht",
    },
  ],
  "zolder alt": [
    {
      start: 0.049,
      name: "Earste",
    },
    {
      start: 0.123,
      name: "Sterrenwachtbocht",
    },
    {
      start: 0.18,
      name: "Kanaalbocht",
    },
    {
      start: 0.26,
      name: "Lucien Bianchbocht",
    },
    {
      start: 0.42,
      name: "Kleine Chicane",
    },
    {
      start: 0.475,
      name: "Sacramentshelling",
    },
    {
      start: 0.521,
      name: "Butte",
    },
    {
      start: 0.57,
      name: "Villeneuve Chicane",
    },
    {
      start: 0.622,
      name: "Terlamenbocht",
    },
    {
      start: 0.74,
      name: "Bolderbergbocht",
    },
    {
      start: 0.776,
      name: "Jochen Rindtbocht",
    },
    {
      start: 0.88,
      name: "Jacky Ickxbocht",
    },
  ],
  "zolder gp": [
    {
      start: 0.049,
      name: "Earste",
    },
    {
      start: 0.123,
      name: "Sterrenwachtbocht",
    },
    {
      start: 0.18,
      name: "Kanaalbocht",
    },
    {
      start: 0.26,
      name: "Lucien Bianchbocht",
    },
    {
      start: 0.42,
      name: "Kleine Chicane",
    },
    {
      start: 0.475,
      name: "Sacramentshelling",
    },
    {
      start: 0.521,
      name: "Butte",
    },
    {
      start: 0.57,
      name: "Villeneuve Chicane",
    },
    {
      start: 0.622,
      name: "Terlamenbocht",
    },
    {
      start: 0.74,
      name: "Bolderbergbocht",
    },
    {
      start: 0.776,
      name: "Jochen Rindtbocht",
    },
    {
      start: 0.88,
      name: "Jacky Ickxbocht",
    },
  ],
};
